const BiblicalCharacter = require('../models/biblical_character');
// src/data/biblicalCharacters.js

const biblicalCharacters = [
  // Male Leaders/Kings
  {
    name: 'David',
    gender: 'male',
    traits: ['bold', 'courageous', 'faithful', 'artistic', 'emotional'],
    leadership: 'direct',
    spiritualStyle: 'expressive',
    challenges: ['facing giants', 'waiting for promises', 'personal failures', 'family conflict'],
    nameThemes: ['beloved', 'chosen', 'leader'],
    category: 'king',
  },
  {
    name: 'Solomon',
    gender: 'male',
    traits: ['wise', 'discerning', 'peaceful', 'wealthy', 'intellectual'],
    leadership: 'judicial',
    spiritualStyle: 'contemplative',
    challenges: ['temptation', 'handling wealth', 'maintaining wisdom', 'idolatry'],
    nameThemes: ['peace', 'wisdom', 'prosperity'],
    category: 'king',
  },
  {
    name: 'Hezekiah',
    gender: 'male',
    traits: ['reformer', 'faithful', 'strategic', 'determined'],
    leadership: 'restorative',
    spiritualStyle: 'devout',
    challenges: ['national revival', 'facing enemies', 'illness', 'pride'],
    nameThemes: ['strengthened by God', 'restoration', 'reform'],
    category: 'king',
  },
  {
    name: 'Josiah',
    gender: 'male',
    traits: ['reformer', 'passionate', 'young', 'dedicated'],
    leadership: 'zealous',
    spiritualStyle: 'reviving',
    challenges: ['early leadership', 'national reform', 'religious restoration'],
    nameThemes: ['healed by God', 'youth leader', 'reformer'],
    category: 'king',
  },

  // Male Prophets/Spiritual Leaders
  {
    name: 'Moses',
    gender: 'male',
    traits: ['humble', 'leader', 'mediator', 'liberator', 'lawgiver'],
    leadership: 'reluctant',
    spiritualStyle: 'intimate with God',
    challenges: ['doubt', 'opposition', 'leadership burden', 'personal frustration'],
    nameThemes: ['drawn out', 'deliverer', 'lawgiver'],
    category: 'prophet',
  },
  {
    name: 'Elijah',
    gender: 'male',
    traits: ['bold', 'fiery', 'zealous', 'miraculous', 'prophetic'],
    leadership: 'confrontational',
    spiritualStyle: 'powerful',
    challenges: ['standing alone', 'fear', 'depression', 'confronting evil'],
    nameThemes: ['my God is Yahweh', 'fire', 'prophet'],
    category: 'prophet',
  },
  {
    name: 'Daniel',
    gender: 'male',
    traits: ['wise', 'principled', 'excellent', 'devoted', 'visionary'],
    leadership: 'exemplary',
    spiritualStyle: 'disciplined',
    challenges: ['standing firm', 'cultural pressure', 'interpretation', 'exile'],
    nameThemes: ['judge', 'wisdom', 'God is my judge'],
    category: 'prophet',
  },
  {
    name: 'Jeremiah',
    gender: 'male',
    traits: ['sensitive', 'persistent', 'sorrowful', 'truthful', 'emotional'],
    leadership: 'prophetic',
    spiritualStyle: 'lament',
    challenges: ['loneliness', 'rejection', 'persecution', 'delivering hard messages'],
    nameThemes: ['appointed', 'tears', 'weeping prophet'],
    category: 'prophet',
  },
  {
    name: 'Isaiah',
    gender: 'male',
    traits: ['eloquent', 'visionary', 'noble', 'poetic', 'prophetic'],
    leadership: 'influential',
    spiritualStyle: 'visionary',
    challenges: ['speaking truth to power', 'vision burden', 'national crisis'],
    nameThemes: ['salvation of the Lord', 'vision', 'prophet'],
    category: 'prophet',
  },

  // Male Disciples/New Testament Leaders
  {
    name: 'Peter',
    gender: 'male',
    traits: ['impulsive', 'bold', 'natural leader', 'passionate', 'transformative'],
    leadership: 'pioneer',
    spiritualStyle: 'action-oriented',
    challenges: ['failure', 'restoration', 'growth through mistakes', 'courage'],
    nameThemes: ['rock', 'foundation', 'changed'],
    category: 'disciple',
  },
  {
    name: 'Paul',
    gender: 'male',
    traits: ['passionate', 'intellectual', 'determined', 'transformative', 'missionary'],
    leadership: 'mentoring',
    spiritualStyle: 'disciplined',
    challenges: ['persecution', 'physical limitations', 'church conflicts', 'past regrets'],
    nameThemes: ['small', 'humble', 'changed'],
    category: 'apostle',
  },
  {
    name: 'John',
    gender: 'male',
    traits: ['loving', 'contemplative', 'visionary', 'devoted', 'spiritual'],
    leadership: 'relational',
    spiritualStyle: 'loving',
    challenges: ['persecution', 'longevity', 'balancing love and truth'],
    nameThemes: ['beloved', 'grace', 'love'],
    category: 'disciple',
  },
  {
    name: 'Timothy',
    gender: 'male',
    traits: ['faithful', 'young', 'teachable', 'emerging leader', 'dependent'],
    leadership: 'apprentice',
    spiritualStyle: 'growing',
    challenges: ['youth', 'health issues', 'gaining respect', 'stepping into leadership'],
    nameThemes: ['honoring God', 'young leader', 'student'],
    category: 'disciple',
  },

  // Male Patriarchs
  {
    name: 'Abraham',
    gender: 'male',
    traits: ['faithful', 'pioneering', 'obedient', 'hospitable', 'legacy builder'],
    leadership: 'patriarch',
    spiritualStyle: 'faithful',
    challenges: ['waiting', 'family conflict', 'moving into unknown', 'trust'],
    nameThemes: ['father of many', 'covenant', 'faith'],
    category: 'patriarch',
  },
  {
    name: 'Joseph',
    gender: 'male',
    traits: ['patient', 'wise', 'forgiving', 'administrative', 'visionary'],
    leadership: 'servant',
    spiritualStyle: 'steady',
    challenges: ['waiting', 'forgiveness', 'staying faithful', 'family reconciliation'],
    nameThemes: ['increase', 'addition', 'blessed'],
    category: 'patriarch',
  },
  {
    name: 'Jacob',
    gender: 'male',
    traits: ['persistent', 'strategic', 'transformative', 'wrestling', 'family-focused'],
    leadership: 'transforming',
    spiritualStyle: 'wrestling',
    challenges: ['deception', 'family conflict', 'personal transformation', 'favoritism'],
    nameThemes: ['supplanter', 'struggles with God', 'transformed'],
    category: 'patriarch',
  },

  // Female Leaders/Judges
  {
    name: 'Deborah',
    gender: 'female',
    traits: ['bold', 'wise', 'leadership', 'prophetic', 'judicial'],
    leadership: 'direct',
    spiritualStyle: 'prophetic',
    challenges: ['leading in difficult times', 'military strategy', 'judgment'],
    nameThemes: ['bee', 'leader', 'prophetess'],
    category: 'judge',
  },
  {
    name: 'Esther',
    gender: 'female',
    traits: ['strategic', 'wise', 'courageous', 'diplomatic', 'beautiful'],
    leadership: 'influential',
    spiritualStyle: 'strategic',
    challenges: ['timing', 'using influence', 'standing for justice', 'hidden faith'],
    nameThemes: ['star', 'hidden', 'beauty'],
    category: 'royal',
  },
  {
    name: 'Miriam',
    gender: 'female',
    traits: ['musical', 'leader', 'prophetic', 'influential', 'supportive'],
    leadership: 'encouraging',
    spiritualStyle: 'expressive',
    challenges: ['jealousy', 'supporting leadership', 'balancing roles'],
    nameThemes: ['rebellion', 'bitter', 'prophet'],
    category: 'prophet',
  },
  {
    name: 'Abigail',
    gender: 'female',
    traits: ['wise', 'diplomatic', 'peacemaker', 'proactive', 'discerning'],
    leadership: 'mediator',
    spiritualStyle: 'prudent',
    challenges: ['difficult marriage', 'peacemaking', 'strategic thinking'],
    nameThemes: ["father's joy", "wisdom", "mediator"],
    category: 'leader',
  },

  // Female Disciples/New Testament Women
  {
    name: 'Mary',
    gender: 'female',
    traits: ['faithful', 'contemplative', 'obedient', 'devoted', 'nurturing'],
    leadership: 'servant',
    spiritualStyle: 'contemplative',
    challenges: ['trust', 'social pressure', 'sacrifice', 'motherhood'],
    nameThemes: ['bitter', 'beloved', 'chosen'],
    category: 'disciple',
  },
  {
    name: 'Mary Magdalene',
    gender: 'female',
    traits: ['devoted', 'transformed', 'faithful', 'witness', 'supportive'],
    leadership: 'witness',
    spiritualStyle: 'devoted',
    challenges: ['past struggles', 'standing firm', 'societal judgment'],
    nameThemes: ['tower', 'witness', 'transformed'],
    category: 'disciple',
  },
  {
    name: 'Priscilla',
    gender: 'female',
    traits: ['teacher', 'hospitable', 'partnership', 'mentor', 'knowledgeable'],
    leadership: 'equipper',
    spiritualStyle: 'teaching',
    challenges: ['ministry partnership', 'relocation', 'teaching others'],
    nameThemes: ['ancient', 'teacher', 'partner'],
    category: 'disciple',
  },
  {
    name: 'Lydia',
    gender: 'female',
    traits: ['businesswoman', 'hospitable', 'generous', 'first convert', 'leader'],
    leadership: 'host',
    spiritualStyle: 'generous',
    challenges: ['business and faith', 'hosting church', 'pioneering'],
    nameThemes: ['noble', 'business leader', 'pioneer'],
    category: 'disciple',
  },

  // Female Matriarchs/Old Testament Women
  {
    name: 'Ruth',
    gender: 'female',
    traits: ['loyal', 'humble', 'hardworking', 'faithful', 'devoted'],
    leadership: 'servant',
    spiritualStyle: 'devoted',
    challenges: ['adaptation', 'loss', 'new beginnings', 'cross-cultural'],
    nameThemes: ['friend', 'companion', 'beauty'],
    category: 'matriarch',
  },
  {
    name: 'Sarah',
    gender: 'female',
    traits: ['faithful', 'beautiful', 'patient', 'motherly', 'doubtful'],
    leadership: 'supportive',
    spiritualStyle: 'waiting',
    challenges: ['waiting', 'doubt', 'laughter', 'promised child'],
    nameThemes: ['princess', 'mother', 'laughter'],
    category: 'matriarch',
  },
  {
    name: 'Hannah',
    gender: 'female',
    traits: ['prayerful', 'faithful', 'dedicated', 'persistent', 'sacrificial'],
    leadership: 'nurturing',
    spiritualStyle: 'prayer',
    challenges: ['infertility', 'rival relationship', 'sacrifice', 'letting go'],
    nameThemes: ['grace', 'favor', 'prayer'],
    category: 'matriarch',
  },

  // Other Significant Male Characters
  {
    name: 'Jonathan',
    gender: 'male',
    traits: ['loyal', 'selfless', 'brave', 'friendship', 'princely'],
    leadership: 'supportive',
    spiritualStyle: 'friendship',
    challenges: ['divided loyalty', 'self-sacrifice', 'friendship vs. family'],
    nameThemes: ['gift of God', 'loyalty', 'friend'],
    category: 'prince',
  },
  {
    name: 'Samuel',
    gender: 'male',
    traits: ['faithful', 'prophetic', 'obedient', 'transitional', 'dedicated'],
    leadership: 'bridge',
    spiritualStyle: 'listening',
    challenges: ['transition', 'spiritual decline', 'hearing God', 'succession'],
    nameThemes: ['heard by God', 'prophet', 'dedicated'],
    category: 'prophet',
  },
  {
    name: 'Nehemiah',
    gender: 'male',
    traits: ['organizer', 'leader', 'rebuilder', 'planner', 'prayerful'],
    leadership: 'administrative',
    spiritualStyle: 'strategic',
    challenges: ['rebuilding', 'opposition', 'organization', 'perseverance'],
    nameThemes: ['comforted by God', 'rebuilder', 'administrator'],
    category: 'leader',
  },
  {
    name: 'Job',
    gender: 'male',
    traits: ['faithful', 'patient', 'questioning', 'resilient', 'righteous'],
    leadership: 'enduring',
    spiritualStyle: 'suffering',
    challenges: ['suffering', 'questioning God', 'loss', 'restoration'],
    nameThemes: ['persecuted', 'tested', 'restored'],
    category: 'patriarch',
  },

  // Other Significant Female Characters
  {
    name: 'Naomi',
    gender: 'female',
    traits: ['resilient', 'bitter', 'restored', 'honest', 'nurturing'],
    leadership: 'mentor',
    spiritualStyle: 'realistic',
    challenges: ['loss', 'bitterness', 'returning home', 'restoration'],
    nameThemes: ['pleasant', 'bitter', 'restored'],
    category: 'matriarch',
  },
  {
    name: 'Tabitha/Dorcas',
    gender: 'female',
    traits: ['servant', 'generous', 'skilled', 'caring', 'impactful'],
    leadership: 'service',
    spiritualStyle: 'generosity',
    challenges: ['serving poor', 'using skills for ministry', 'community impact'],
    nameThemes: ['gazelle', 'servant', 'skilled'],
    category: 'disciple',
  },
  {
    name: 'Elizabeth',
    gender: 'female',
    traits: ['faithful', 'patient', 'righteous', 'elder', 'supportive'],
    leadership: 'mentoring',
    spiritualStyle: 'faithful',
    challenges: ['waiting', 'late blessing', 'supporting others', 'raising special child'],
    nameThemes: ['God is my oath', 'faithful', 'elderly blessing'],
    category: 'matriarch',
  },
  {
    name: 'Martha',
    gender: 'female',
    traits: ['practical', 'service-oriented', 'responsible', 'direct', 'hospitable'],
    leadership: 'service',
    spiritualStyle: 'active',
    challenges: ['balancing service and worship', 'worry', 'responsibility'],
    nameThemes: ['lady', 'servant', 'practical'],
    category: 'disciple',
  }
];

// Add this to your initial setup script
async function seedCharacters() {
  try {
    await BiblicalCharacter.deleteMany({});
    await BiblicalCharacter.insertMany(biblicalCharacters);
    console.log('Biblical characters seeded successfully');
  } catch (error) {
    console.error('Error seeding characters:', error);
  }
}

module.exports = { seedCharacters, biblicalCharacters };